#!/usr/bin/env python3
"""
batch-sqlite.py

Implements the "Database Delegation Workflow" from
skills/high-vs-low/references/batch-handling.md.

Follows the exact steps:
  1. Discover schema
  2. Preview records
  3. Delegate evaluation per-record (calls AI endpoint)
  4. Delegate review per-record (calls AI endpoint)
  5. Report summary

Usage:
  python3 batch-sqlite.py <db_path> [options]

Options:
  --limit N          Process only the first N records (default: all)
  --start-id ID      Start from this record ID (default: minimum ID)
  --endpoint URL     OpenAI-compatible endpoint URL (default: env OPENAI_ENDPOINT or http://127.0.0.1:1234/v1)
  --api-key KEY      API key (default: env OPENAI_API_KEY)
  --model MODEL      Model name (default: qwen3.6-27b-mtp)
  --stub             Use a stub AI that returns a constant response
  --skip-review      Skip the review phase
  --skip-evaluation  Skip the evaluation phase
  --dry-run          Print what would be done without modifying the database
  --reset            Clean out evaluation/count/score columns before processing
  --reset-only       Only clean out evaluation/count/score columns and exit
  --where CLAUSE     SQL WHERE clause (without 'WHERE') to filter records
  --report-type TYPE basic or detailed (default: basic)
"""

import argparse
import json
import os
import re
import sqlite3
import sys
import time
import urllib.error
import urllib.request


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

STUB_EVALUATION = """# High Law vs Low Law Alignment Evaluation: STUB_DOCUMENT

## Overview

This is a STUB_EVALUATION_RESPONSE generated by the batch-sqlite.py stub client.
The document was evaluated for High Law vs Low Law alignment.

---

## Key Topics

1. **Authority and Power: Obedience**: Discussion of obedience to authority
2. **Justice and Punishment: Divine Justice**: References to divine justice
3. **Mercy and Compassion: Forgiveness**: Themes of mercy and forgiveness
4. **Autonomy and Consent: Free Will**: Discussion of individual agency
5. **Community and Belonging: Unity**: Themes of community unity

---

## Statement Quotes

### High Law Aligned (2 statements)

| # | Location | Rules | Principle Quote | Speaker | Stance Quote | Key Topics | Decision Notes |
|---| -------- | ----- | --------------- | ------- | ------------ | ---------- | -------------- |
| 1 | Line 5 | 6-HL,37-HL | "individual agency and choice" | Author | "each person must choose for themselves" | Authority and Power: Obedience, Autonomy and Consent: Free Will | HL principle (autonomy), author supports = HL |
| 2 | Line 12 | 26-HL,5-HL | "compassion for the suffering" | Author | "we must show mercy to all" | Mercy and Compassion: Forgiveness | HL principle (liberating mercy), author supports = HL |

### Low Law Aligned (3 statements)

| # | Location | Rules | Principle Quote | Speaker | Stance Quote | Key Topics | Decision Notes |
|---| -------- | ----- | --------------- | ------- | ------------ | ---------- | -------------- |
| 1 | Line 8 | 17-LL,19-LL | "obey under threat of punishment" | Author | "you must obey or face consequences" | Authority and Power: Obedience | LL principle (divine coercion), author supports = LL |
| 2 | Line 15 | 25-LL,27-LL | "punishment for transgression" | Author | "the wicked shall be punished" | Justice and Punishment: Divine Justice | LL principle (punitive justice), author supports = LL |
| 3 | Line 20 | 34-LL,35-LL | "conformity to the standard" | Author | "those who do not conform will be cast out" | Community and Belonging: Unity | LL principle (conformity), author supports = LL |

---

## Scoring Summary

| Category | Count | Percentage |
| -------- | ----- | ---------- |
| High Law Aligned | 2 | 40.0% |
| Low Law Aligned | 3 | 60.0% |
| **Total** | **5** | **100%** |

**Score**: ((40.0 - 60.0) / 10) = **-2.0**

---

## Key Topic Score Table

| Key Topic | High # | Low # | Score |
| --------- | ------ | ----- | ----- |
| Authority and Power: Obedience | 1 | 1 | 0.0 |
| Justice and Punishment: Divine Justice | 0 | 1 | -10.0 |
| Mercy and Compassion: Forgiveness | 1 | 0 | 10.0 |
| Autonomy and Consent: Free Will | 1 | 0 | 10.0 |
| Community and Belonging: Unity | 0 | 1 | -10.0 |
"""

STUB_REVIEW = """# Review Result: STUB_REVIEW_RESPONSE

The evaluation has been reviewed against the checklist.

**Changes made during review**: None. The stub evaluation is internally consistent.

**Original counts**: HL=2, LL=3, Score=-2.0
**Updated counts**: HL=2, LL=3, Score=-2.0

The evaluation report is valid. No changes required.
"""


# ---------------------------------------------------------------------------
# OpenAI-compatible client
# ---------------------------------------------------------------------------

class OpenAIClient:
    """Minimal OpenAI-compatible chat completions client using urllib."""

    def __init__(self, endpoint, api_key, model="gpt-4o"):
        self.endpoint = endpoint.rstrip("/")
        self.api_key = api_key
        self.model = model

    def chat(self, system_prompt, user_prompt, temperature=0.0):
        """Send a chat completion request and return the assistant message."""
        url = f"{self.endpoint}/chat/completions"
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": temperature,
        }
        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            url,
            data=data,
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {self.api_key}",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=300) as resp:
                body = json.loads(resp.read().decode("utf-8"))
                return body["choices"][0]["message"]["content"]
        except urllib.error.HTTPError as exc:
            error_body = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(
                f"HTTP {exc.code} from {url}: {error_body}"
            ) from exc


class StubClient:
    """Stub that returns constant responses for testing."""

    def __init__(self):
        self.call_count = 0

    def chat(self, system_prompt, user_prompt, temperature=0.0):
        self.call_count += 1
        if "review" in system_prompt.lower() or "review" in user_prompt.lower():
            return STUB_REVIEW
        return STUB_EVALUATION


# ---------------------------------------------------------------------------
# Prompt builders
# ---------------------------------------------------------------------------

EVALUATION_SYSTEM_PROMPT = """You are a High Law vs Low Law alignment evaluator.

Read the provided text and produce a complete evaluation report following this structure:

1. Extract ALL normative statements with stances on moral/legal principles
2. Classify each as High Law or Low Law aligned using the Distinction Rule Table
3. Assign key topics using the Root Taxonomy
4. Calculate scores: Score = (HL_pct - LL_pct) / 10 on scale -10 to +10

Produce a markdown report with these EXACT sections:
- # High Law vs Low Law Alignment Evaluation: {title}
- ## Overview
- ## Key Topics (numbered list, 5-14 topics)
- ## Statement Quotes with ### High Law Aligned (N statements) and ### Low Law Aligned (N statements) subsections
  Each with table: | # | Location | Rules | Principle Quote | Speaker | Stance Quote | Key Topics | Decision Notes |
- ## Scoring Summary table with HL/LL counts, percentages, and Score formula
- ## Key Topic Score Table with columns: Key Topic | High # | Low # | Score

Ensure counts in headers match actual table rows. Ensure scoring is mathematically correct."""


REVIEW_SYSTEM_PROMPT = """You are a High Law vs Low Law evaluation report reviewer.

You will receive the original document text and an existing evaluation report.
Review the evaluation against this checklist:

1. Verify all normative stances in the source text are captured
2. Verify HL/LL table header counts match actual rows
3. Verify scoring math: Score = (HL_pct - LL_pct) / 10
4. Verify Key Topic Score Table counts match statement assignments
5. Verify bidirectional topic consistency (list <-> statements)
6. Verify Decision Notes are internally consistent

Return your review result with:
- Original counts: HL=N, LL=N, Score=X.X
- Updated counts: HL=N, LL=N, Score=X.X (same if no changes)
- Description of any changes made
- If no changes, state that no changes are required."""


def build_evaluation_user_prompt(doc_text, doc_title):
    return f"""Evaluate the following document for High Law vs Low Law alignment.

Document Title: {doc_title}

Document Text:
---
{doc_text}
---

Produce the complete evaluation report as specified."""


def build_review_user_prompt(doc_text, evaluation, doc_title):
    return f"""Review the following evaluation report for the document titled "{doc_title}".

Original Document Text:
---
{doc_text}
---

Existing Evaluation Report:
---
{evaluation}
---

Review the evaluation for accuracy, completeness, and consistency.
Report original and updated counts."""


# ---------------------------------------------------------------------------
# Report parsing
# ---------------------------------------------------------------------------

def parse_evaluation_report(report_text):
    """Extract count_hl, count_ll, and score from an evaluation report."""
    # Try to get counts from the Scoring Summary table
    hl_match = re.search(
        r"High Law Aligned\s+\|?\s+(\d+)", report_text
    )
    ll_match = re.search(
        r"Low Law Aligned\s+\|?\s+(\d+)", report_text
    )

    # Also try header counts as fallback
    if not hl_match:
        hl_match = re.search(
            r"### High Law Aligned \((\d+) statements?\)", report_text
        )
    if not ll_match:
        ll_match = re.search(
            r"### Low Law Aligned \((\d+) statements?\)", report_text
        )

    count_hl = int(hl_match.group(1)) if hl_match else 0
    count_ll = int(ll_match.group(1)) if ll_match else 0

    # Try to get score from the report
    score = None
    score_match = re.search(
        r"\*\*Score\*\*.*?=\s*\*\*([+-]?\d+\.?\d*)\*\*", report_text
    )
    if score_match:
        score = float(score_match.group(1))
    else:
        # Calculate from counts
        total = count_hl + count_ll
        if total > 0:
            hl_pct = 100 * count_hl / total
            ll_pct = 100 * count_ll / total
            score = round((hl_pct - ll_pct) / 10, 1)

    return count_hl, count_ll, score


def parse_review_result(review_text):
    """Extract updated counts from a review result."""
    # Try "Updated counts" line
    updated_match = re.search(
        r"Updated counts.*?HL\s*=\s*(\d+).*?LL\s*=\s*(\d+).*?Score\s*=\s*([+-]?\d+\.?\d*)",
        review_text,
        re.DOTALL,
    )
    if updated_match:
        return (
            int(updated_match.group(1)),
            int(updated_match.group(2)),
            float(updated_match.group(3)),
        )

    # Fallback: try to parse from the full review text
    hl_match = re.search(r"HL\s*=\s*(\d+)", review_text)
    ll_match = re.search(r"LL\s*=\s*(\d+)", review_text)
    score_match = re.search(r"Score\s*=\s*([+-]?\d+\.?\d*)", review_text)

    if hl_match and ll_match and score_match:
        return (
            int(hl_match.group(1)),
            int(ll_match.group(1)),
            float(score_match.group(1)),
        )

    return None, None, None


# ---------------------------------------------------------------------------
# Database operations
# ---------------------------------------------------------------------------

def discover_schema(conn):
    """Step 1: Discover schema by querying sqlite_master."""
    cursor = conn.cursor()
    cursor.execute(
        "SELECT sql FROM sqlite_master WHERE type='table' AND name='documents'"
    )
    row = cursor.fetchone()
    if not row:
        print("ERROR: No 'documents' table found in the database.")
        sys.exit(1)
    schema = row[0]
    print("[Step 1] Schema discovered:")
    print(schema)
    print()

    # Verify required columns exist
    required = {"id", "doc_text", "evaluation", "count_hl", "count_ll", "score"}
    found = {m[0] for m in re.findall(r"(\w+)\s+(TEXT|INTEGER|REAL)", schema, re.IGNORECASE)}
    missing = required - found
    if missing:
        print(f"ERROR: Missing required columns: {missing}")
        sys.exit(1)
    print(f"[Step 1] All required columns present: {required}")
    print()
    return schema


def preview_records(conn, limit=None, start_id=None, where_clause=None):
    """Step 2: Preview records - check id range, text lengths, evaluation state."""
    cursor = conn.cursor()

    cursor.execute("SELECT MIN(id), MAX(id), COUNT(*) FROM documents")
    min_id, max_id, total = cursor.fetchone()

    cursor.execute("SELECT AVG(LENGTH(doc_text)), MIN(LENGTH(doc_text)), MAX(LENGTH(doc_text)) FROM documents")
    avg_len, min_len, max_len = cursor.fetchone()

    cursor.execute("SELECT COUNT(*) FROM documents WHERE evaluation IS NOT NULL")
    evaluated = cursor.fetchone()[0]

    cursor.execute("SELECT COUNT(*) FROM documents WHERE evaluation IS NULL")
    unevaluated = cursor.fetchone()[0]

    print("[Step 2] Record preview:")
    print(f"  ID range: {min_id} - {max_id}")
    print(f"  Total records: {total}")
    print(f"  Text lengths: avg={avg_len:.0f}, min={min_len}, max={max_len}")
    print(f"  Already evaluated: {evaluated}")
    print(f"  Unevaluated: {unevaluated}")

    # Determine which records to process
    conditions = []
    params = []
    if where_clause is not None:
        conditions.append(where_clause)
    if start_id is not None:
        conditions.append("id >= ?")
        params.append(start_id)

    if conditions:
        cursor.execute(
            "SELECT COUNT(*) FROM documents WHERE " + " AND ".join(conditions), params
        )
    else:
        cursor.execute("SELECT COUNT(*) FROM documents")
    eligible = cursor.fetchone()[0]

    if limit and limit < eligible:
        eligible = limit

    print(f"  Records to process: {eligible}")
    print()

    return min_id, max_id, total


def reset_evaluations(conn, where_clause=None):
    """Clean out evaluation, count_hl, count_ll, and score columns."""
    cursor = conn.cursor()
    query = "UPDATE documents SET evaluation = NULL, count_hl = NULL, count_ll = NULL, score = NULL"
    if where_clause is not None:
        query += f" WHERE {where_clause}"
    cursor.execute(query)
    conn.commit()
    print(f"[Reset] Cleared evaluations for {cursor.rowcount} records.")
    print()


def get_records_to_process(conn, limit=None, start_id=None, where_clause=None):
    """Get the list of (id, doc_title, doc_text) to process."""
    cursor = conn.cursor()
    query = "SELECT id, doc_title, doc_text FROM documents"

    # Build WHERE clause from all filters
    conditions = []
    params = []
    if where_clause is not None:
        conditions.append(where_clause)
    if start_id is not None:
        conditions.append("id >= ?")
        params.append(start_id)

    if conditions:
        query += " WHERE " + " AND ".join(conditions)
    query += " ORDER BY id"
    if limit is not None:
        query += " LIMIT ?"
        params.append(limit)

    cursor.execute(query, params)
    return cursor.fetchall()


def save_evaluation(conn, doc_id, evaluation, count_hl, count_ll, score):
    """Save evaluation results to the database."""
    cursor = conn.cursor()
    cursor.execute(
        """UPDATE documents
           SET evaluation = ?, count_hl = ?, count_ll = ?, score = ?
           WHERE id = ?""",
        (evaluation, count_hl, count_ll, score, doc_id),
    )
    conn.commit()


def load_record(conn, doc_id):
    """Load a single record's doc_text, doc_title, and evaluation."""
    cursor = conn.cursor()
    cursor.execute(
        "SELECT id, doc_title, doc_text, evaluation FROM documents WHERE id = ?",
        (doc_id,),
    )
    row = cursor.fetchone()
    if not row:
        return None
    return {"id": row[0], "doc_title": row[1], "doc_text": row[2], "evaluation": row[3]}


# ---------------------------------------------------------------------------
# Workflow steps
# ---------------------------------------------------------------------------

def step3_evaluate(conn, client, records, dry_run=False, report_type="basic"):
    """Step 3: Delegate evaluation per-record."""
    print("=" * 60)
    print("[Step 3] Evaluation Phase")
    print("=" * 60)
    print()

    results = []
    for idx, (doc_id, doc_title, doc_text) in enumerate(records, 1):
        print(f"[{idx}/{len(records)}] Evaluating ID={doc_id}: {doc_title}")

        # Build prompts
        system_prompt = EVALUATION_SYSTEM_PROMPT.format(title=doc_title)
        user_prompt = build_evaluation_user_prompt(doc_text, doc_title)

        # Call AI endpoint
        try:
            response = client.chat(system_prompt, user_prompt)
        except RuntimeError as exc:
            print(f"  ERROR: {exc}")
            results.append((doc_id, doc_title, None, None, None, None, str(exc)))
            continue

        # Parse results
        count_hl, count_ll, score = parse_evaluation_report(response)
        print(f"  Result: HL={count_hl}, LL={count_ll}, Score={score}")

        if not dry_run:
            save_evaluation(conn, doc_id, response, count_hl, count_ll, score)
            print(f"  Saved to database.")

        # Verify
        record = load_record(conn, doc_id)
        if record and record["evaluation"] is not None:
            print(f"  Verified: evaluation populated ({len(record['evaluation'])} chars)")
        else:
            print(f"  WARNING: evaluation not found in database after save")

        results.append((doc_id, doc_title, count_hl, count_ll, score, response, None))
        print()

    return results


def step4_review(conn, client, records, eval_results, dry_run=False):
    """Step 4: Delegate review per-record."""
    print("=" * 60)
    print("[Step 4] Review Phase")
    print("=" * 60)
    print()

    review_results = []
    for idx, (doc_id, doc_title, doc_text) in enumerate(records, 1):
        print(f"[{idx}/{len(records)}] Reviewing ID={doc_id}: {doc_title}")

        # Load current evaluation
        record = load_record(conn, doc_id)
        if not record or record["evaluation"] is None:
            print(f"  SKIPPED: No evaluation found for ID={doc_id}")
            review_results.append((doc_id, doc_title, None, None, None, None, None, None, "No evaluation"))
            continue

        # Get original counts from eval_results
        orig_hl = None
        orig_ll = None
        orig_score = None
        for r in eval_results:
            if r[0] == doc_id:
                orig_hl, orig_ll, orig_score = r[2], r[3], r[4]
                break

        # Build prompts
        system_prompt = REVIEW_SYSTEM_PROMPT
        user_prompt = build_review_user_prompt(
            record["doc_text"], record["evaluation"], doc_title
        )

        # Call AI endpoint
        try:
            response = client.chat(system_prompt, user_prompt)
        except RuntimeError as exc:
            print(f"  ERROR: {exc}")
            review_results.append((doc_id, doc_title, orig_hl, orig_ll, orig_score, None, None, None, str(exc)))
            continue

        # Parse review results
        new_hl, new_ll, new_score = parse_review_result(response)

        print(f"  Original: HL={orig_hl}, LL={orig_ll}, Score={orig_score}")
        print(f"  Updated:  HL={new_hl}, LL={new_ll}, Score={new_score}")

        # Update if changed
        changed = (new_hl != orig_hl) or (new_ll != orig_ll) or (new_score != orig_score)
        if changed and not dry_run:
            # Update counts/score; keep or update evaluation based on review
            save_evaluation(conn, doc_id, record["evaluation"], new_hl, new_ll, new_score)
            print(f"  Updated database with new counts/score.")
        elif not dry_run:
            print(f"  No changes needed.")

        # Verify
        record = load_record(conn, doc_id)
        if record and record["evaluation"] is not None:
            print(f"  Verified: evaluation present ({len(record['evaluation'])} chars)")
        else:
            print(f"  WARNING: evaluation missing after review")

        review_results.append((doc_id, doc_title, orig_hl, orig_ll, orig_score, new_hl, new_ll, new_score, None))
        print()

    return review_results


def step5_report(eval_results, review_results):
    """Step 5: Report summary."""
    print("=" * 60)
    print("[Step 5] Summary Report")
    print("=" * 60)
    print()

    print("EVALUATION RESULTS:")
    print(f"  {'ID':>6}  {'Title':<50}  {'HL':>3}  {'LL':>3}  {'Score':>6}  {'Error'}")
    print("  " + "-" * 100)
    for r in eval_results:
        doc_id, doc_title, hl, ll, score, _, error = r[0], r[1], r[2], r[3], r[4], r[5], r[6]
        title_display = doc_title[:48] if doc_title else "N/A"
        hl_str = str(hl) if hl is not None else "N/A"
        ll_str = str(ll) if ll is not None else "N/A"
        score_str = f"{score:.1f}" if score is not None else "N/A"
        error_str = error[:20] if error else ""
        print(f"  {doc_id:>6}  {title_display:<50}  {hl_str:>3}  {ll_str:>3}  {score_str:>6}  {error_str}")

    if review_results:
        print()
        print("REVIEW RESULTS:")
        print(f"  {'ID':>6}  {'Title':<50}  {'Orig HL':>7}  {'Orig LL':>7}  {'Orig Score':>10}  {'New HL':>6}  {'New LL':>6}  {'New Score':>9}  {'Error'}")
        print("  " + "-" * 130)
        for r in review_results:
            doc_id = r[0]
            doc_title = r[1] if len(r) > 1 else ""
            title_display = doc_title[:45] if doc_title else "N/A"
            orig_hl = str(r[2]) if r[2] is not None else "N/A"
            orig_ll = str(r[3]) if r[3] is not None else "N/A"
            orig_score = f"{r[4]:.1f}" if r[4] is not None else "N/A"
            new_hl = str(r[5]) if r[5] is not None else "N/A"
            new_ll = str(r[6]) if r[6] is not None else "N/A"
            new_score = f"{r[7]:.1f}" if r[7] is not None else "N/A"
            error = r[8] if len(r) > 8 and r[8] else ""
            error_str = error[:15] if error else ""
            print(f"  {doc_id:>6}  {title_display:<45}  {orig_hl:>7}  {orig_ll:>7}  {orig_score:>10}  {new_hl:>6}  {new_ll:>6}  {new_score:>9}  {error_str}")

    print()
    print("Workflow complete.")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Database Delegation Workflow for High Law vs Low Law evaluation"
    )
    parser.add_argument("db_path", help="Path to SQLite database")
    parser.add_argument("--limit", type=int, default=None, help="Process only first N records")
    parser.add_argument("--start-id", type=int, default=None, help="Start from this record ID")
    parser.add_argument("--endpoint", default=os.environ.get("OPENAI_ENDPOINT", "http://127.0.0.1:1234/v1"), help="OpenAI-compatible endpoint URL")
    parser.add_argument("--api-key", default=os.environ.get("OPENAI_API_KEY", ""), help="API key")
    parser.add_argument("--model", default="qwen3.6-27b-mtp", help="Model name")
    parser.add_argument("--stub", action="store_true", help="Use stub AI client (constant response)")
    parser.add_argument("--skip-review", action="store_true", help="Skip the review phase")
    parser.add_argument("--skip-evaluation", action="store_true", help="Skip the evaluation phase")
    parser.add_argument("--dry-run", action="store_true", help="Print actions without modifying database")
    parser.add_argument("--reset", action="store_true", help="Reset evaluation data before processing")
    parser.add_argument("--reset-only", action="store_true", help="Only reset evaluation data and exit (no eval)")
    parser.add_argument("--where", default=None, help="SQL WHERE clause (without 'WHERE') to filter records")
    parser.add_argument("--report-type", choices=["basic", "detailed"], default="basic", help="Report type")

    args = parser.parse_args()

    # Normalize --endpoint: if it's just an IP/host, build a full URL
    DEFAULT_ENDPOINT = "http://127.0.0.1:1234/v1"
    if not args.endpoint.startswith("http://") and not args.endpoint.startswith("https://"):
        args.endpoint = f"http://{args.endpoint}:1234/v1"
        print(f"[Config] Normalized endpoint to: {args.endpoint}")

    # Validate database path
    if not os.path.exists(args.db_path):
        print(f"ERROR: Database not found: {args.db_path}")
        sys.exit(1)

    # Connect to database
    conn = sqlite3.connect(args.db_path)
    print(f"[DB] Connected: {args.db_path}")

    try:
        # Step 1: Discover schema
        discover_schema(conn)

        # Step 2: Preview records
        preview_records(conn, limit=args.limit, start_id=args.start_id, where_clause=args.where)

        # Reset evaluations (if --reset or --reset-only is passed)
        if args.reset or args.reset_only:
            if not args.dry_run:
                reset_evaluations(conn, where_clause=args.where)
            else:
                print("[Dry-run] Would reset evaluations.")
                print()

            if args.reset_only:
                print("Reset complete. Exiting.")
                return

        # Initialize client (only needed if not skipping both phases)
        if args.skip_evaluation and args.skip_review:
            client = None
            print("[Config] Skipping both evaluation and review — no client needed")
        elif args.stub:
            client = StubClient()
            print(f"[Config] Using STUB client (constant responses)")
        else:
            if not args.endpoint:
                print("ERROR: --endpoint is required")
                sys.exit(1)
            client = OpenAIClient(args.endpoint, args.api_key, args.model)
            print(f"[Config] Endpoint: {args.endpoint}, Model: {args.model}")
        print()

        # Get records to process
        records = get_records_to_process(conn, limit=args.limit, start_id=args.start_id, where_clause=args.where)
        if not records:
            print("No records to process.")
            return

        print(f"Processing {len(records)} records...")
        print()

        # Step 3: Evaluate each record
        if args.skip_evaluation:
            print("[Skipped] Evaluation phase skipped by --skip-evaluation")
            eval_results = []
        else:
            eval_results = step3_evaluate(
                conn, client, records, dry_run=args.dry_run, report_type=args.report_type
            )

        # Step 4: Review each record (unless skipped)
        if args.skip_review:
            print("[Skipped] Review phase skipped by --skip-review")
            review_results = []
        else:
            review_results = step4_review(
                conn, client, records, eval_results, dry_run=args.dry_run
            )

        # Step 5: Report
        step5_report(eval_results, review_results)

    finally:
        conn.close()
        print()
        print(f"[DB] Disconnected.")


if __name__ == "__main__":
    main()
